name: Build Community .srs Files

on:
  push:
    tags:
      - '*'  # триггер на любой новый тег

jobs:
  generate-community-srs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare Sing-Box refilter directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/sing-box-files/refilter

        # Копируем community файлы
        cp community.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/
        cp community_ips.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/

    - name: Generate .srs Files
      run: |
        cd $GITHUB_WORKSPACE/src/sing-box-files

        # Убедимся, что скрипт выполняемый
        chmod +x generate-geoip-geosite

        # Генерация community.srs и community_ip.srs
        ./generate-geoip-geosite -i ./refilter/community.lst -o ./refilter/community.srs
        ./generate-geoip-geosite -i ./refilter/community_ips.lst -o ./refilter/community_ip.srs

    - name: Verify Output
      run: |
        echo "Содержимое refilter после генерации .srs:"
        ls -la $GITHUB_WORKSPACE/src/sing-box-files/refilter

    - name: Upload .srs Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: community-srs-files
        path: $GITHUB_WORKSPACE/src/sing-box-files/refilter/

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "Automatic community.srs release for tag ${{ github.ref_name }}"
        files: |
          $GITHUB_WORKSPACE/src/sing-box-files/refilter/community.srs
          $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip.srs
