name: Build Community .srs Files

on:
  push:
    tags:
      - '*'  # Триггер на любой новый тег

jobs:
  generate-community-srs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare Sing-Box refilter directories
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/sing-box-files/refilter/community
        mkdir -p $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip

        # Копируем community файлы в соответствующие папки
        cp community.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/community/
        cp community_ips.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip/

    - name: Generate .srs Files
      run: |
        cd $GITHUB_WORKSPACE/src/sing-box-files
        chmod +x generate-geoip-geosite

        # Генерация community.srs и community_ip.srs
        ./generate-geoip-geosite -i ./refilter/community -o ./refilter/community.srs
        ./generate-geoip-geosite -i ./refilter/community_ip -o ./refilter/community_ip.srs

    - name: Verify Output
      run: |
        echo "Содержимое refilter после генерации .srs:"
        ls -la $GITHUB_WORKSPACE/src/sing-box-files/refilter

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "Automatic community.srs release for tag ${{ github.ref_name }}"
        prerelease: false

    - name: Upload community.srs
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/src/sing-box-files/refilter/community.srs
        asset_name: community.srs
        asset_content_type: application/octet-stream

    - name: Upload community_ip.srs
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip.srs
        asset_name: community_ip.srs
        asset_content_type: application/octet-stream
