name: Build Custom .srs Files

on:
  workflow_dispatch:  # ручной запуск
  schedule:
    - cron: '0 0 */6 * *' # каждые 6 дней в полночь UTC

jobs:
  generate-srs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare Sing-Box refilter directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/sing-box-files/refilter

        # Копируем нужные входные файлы
        cp community.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/
        cp community_ips.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/
        cp youtube.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/
        cp youtube_ips.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/

    - name: Generate .srs Files
      run: |
        cd $GITHUB_WORKSPACE/src/sing-box-files

        # Убедимся, что скрипт выполняемый
        chmod +x generate-geoip-geosite

        # Генерация community.srs и community_ip.srs
        ./generate-geoip-geosite -i ./refilter/community.lst -o ./refilter/youtube.srs
        ./generate-geoip-geosite -i ./refilter/community_ips.lst -o ./refilter/youtube_ip_ip.srs

    - name: Verify Output
      run: |
        echo "Содержимое refilter после генерации .srs:"
        ls -la $GITHUB_WORKSPACE/src/sing-box-files/refilter

    - name: Upload .srs Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: srs-files
        path: $GITHUB_WORKSPACE/src/sing-box-files/refilter/
