name: Build Community .srs Files

on:
  workflow_dispatch: # Allows manual trigger of the workflow
  schedule:
    - cron: '0 0 */6 * *' # Runs every 6th day at midnight UTC

jobs:
  build-community:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare refilter directories
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/sing-box-files/refilter/community
        mkdir -p $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip

        cp community.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/community/
        cp community_ips.lst $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip/

    - name: Generate .srs Files
      run: |
        cd $GITHUB_WORKSPACE/src/sing-box-files
        chmod +x generate-geoip-geosite

        ./generate-geoip-geosite -i ./refilter/community -o ./refilter/community.srs
        ./generate-geoip-geosite -i ./refilter/community_ip -o ./refilter/community_ip.srs

    - name: Verify generated files
      run: |
        ls -la $GITHUB_WORKSPACE/src/sing-box-files/refilter

    - name: Set Release Name and Tag
      run: |
        CURRENT_DATE=$(date +%d-%m-%Y)
        CURRENT_TAG=$(date +%d%m%Y)
        RELEASE_NAME="Release $CURRENT_DATE"
        TAG_NAME="$CURRENT_TAG"
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Create Pre-release with gh CLI
      run: |
        gh release create "$TAG_NAME" \
          $GITHUB_WORKSPACE/src/sing-box-files/refilter/community.srs \
          $GITHUB_WORKSPACE/src/sing-box-files/refilter/community_ip.srs \
          --title "$RELEASE_NAME" \
          --notes "Automatic $RELEASE_NAME creation for community lists." \
          --draft \
          --prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify Release
      run: |
        gh release view "$TAG_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
